<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="_1" nsURI="http://scap.nist.gov/schema/reporting-core/1.1" nsPrefix="_1">
  <eAnnotations>
    <details key="appinfo" value="&#xA;            &lt;schema>Reporting Core&lt;/schema>&#xA;            &lt;author>David Waltermire, Adam Halbardier, John Wunder&lt;/author>&#xA;            &lt;version>1.1.0&lt;/version>&#xA;            &lt;date>2011-06-02&lt;/date>&#xA;        "/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="RelationshipsContainerType">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="relationships-container-type"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relationships" eType="#//RelationshipsType"
        containment="true" resolveProxies="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Contains a collection of relationship elements."/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="relationships"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationshipsType">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="relationships_._type"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relationship" lowerBound="1"
        upperBound="-1" eType="#//RelationshipType" containment="true" resolveProxies="false">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="relationship"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationshipType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The relationship-type encapsulates a complete relationship from a subject to one or more&#xA;                objects. It is the responsibility of the XML Schema adopting this type to implement the necessary&#xA;                id/idref instances to ensure that @subject and ref refer to valid elements."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="relationship-type"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" unique="false" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//NCName">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Must contain the ID of the object of the relationship being established. The&#xA;                        implementing XML Schema of relationship-type SHOULD implement the necessary id/idref constructs&#xA;                        to ensure a valid reference is constructed."/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="ref"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scope" eType="#//ScopeType"
        defaultValueLiteral="inclusive" unsettable="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates how multiple &lt;ref> elements should be interpreted in this&#xA;                    relationship. If &quot;inclusive&quot; is specified, then the relationship being defined is between the&#xA;                    subject and the collection of objects indicated by the &lt;ref> elements (i.e. the&#xA;                    relationship is not necessarily relevant for any one particular object being referenced, but for the&#xA;                    collection of objects referenced). If &quot;exclusive&quot; is specified, then the relationship being defined&#xA;                    is between the content payload and each object individually (i.e. this is the same as specifying&#xA;                    multiple relationship elements, each with the same @type and subject)."/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="scope"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subject" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//NCName">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Must contain the ID of the subject of the relationship being established. The&#xA;                    implementing XML Schema of relationship-type SHOULD implement the necessary id/idref constructs to&#xA;                    ensure a valid reference is constructed."/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="subject"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//QName">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Specifies the type of relationship (predicate) being defined between the subject and&#xA;                    the object of the relationship. The value is a QName that should reference a term in a controlled&#xA;                    vocabulary which is understood by both the producing and consuming parties."/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="type"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anyAttribute" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A placeholder so that content creators can add attributes as&#xA;                    desired."/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attributeWildcard"/>
        <details key="wildcards" value="##other"/>
        <details key="name" value=":4"/>
        <details key="processing" value="strict"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ScopeType">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="scope_._type"/>
    </eAnnotations>
    <eLiterals name="inclusive"/>
    <eLiterals name="exclusive" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ScopeTypeObject" instanceClassName="org.eclipse.emf.common.util.Enumerator">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="scope_._type:Object"/>
      <details key="baseType" value="scope_._type"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
